apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
      # clusterIP: None  # Headless Service: Pod의 고정 IP가 아닌 이름을 찾아가기 위함
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis-service"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data  # Redis가 데이터를 저장하는 내부 경로
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc  # Step 1에서 만든 PVC와 연결
